# Generated by Django 5.1.5 on 2025-02-02 14:14

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('root', '0017_project_delete_service'),
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('scheduled', models.DateTimeField(default=django.utils.timezone.now)),
                ('content', models.TextField(default='test')),
                ('name_servise', models.CharField(default='Default Service ', max_length=100)),
                ('about_content', models.TextField(default='test')),
                ('image', models.ImageField(default='services.jpg', upload_to='services')),
                ('Edelectus_content_name', models.TextField(default='test')),
                ('Edelectus_content_Description', models.TextField(default='test')),
                ('Temporibus_content_name', models.TextField(default='test')),
                ('Temporibus_content_Description', models.TextField(default='test')),
                ('Feature_content', models.TextField(default='test')),
                ('Description_content_name', models.TextField(default='test')),
                ('Description_content_Description', models.TextField(default='test')),
                ('status', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ('created_at',),
            },
        ),
        migrations.DeleteModel(
            name='Project',
        ),
    ]
