# Generated by Django 4.2 on 2025-02-02 21:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('root', '0018_service_delete_project'),
    ]

    operations = [
        migrations.RenameField(
            model_name='resume',
            old_name='name0',
            new_name='FIRST_TEXT',
        ),
        migrations.RenameField(
            model_name='resume',
            old_name='name1',
            new_name='NAME',
        ),
        migrations.RenameField(
            model_name='resume',
            old_name='name2',
            new_name='SECOND_TEXT',
        ),
        migrations.RenameField(
            model_name='resume',
            old_name='name3',
            new_name='SUBJECT',
        ),
        migrations.RenameField(
            model_name='resume',
            old_name='name4',
            new_name='THIRD_TEXT',
        ),
        migrations.RenameField(
            model_name='resume',
            old_name='name5',
            new_name='TITLE',
        ),
        migrations.AlterField(
            model_name='service',
            name='image',
            field=models.ImageField(default='services/default.jpg', upload_to='services'),
        ),
    ]
