# Generated by Django 4.2 on 2025-02-02 21:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('root', '0019_rename_name0_resume_first_text_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='resume',
            old_name='content',
            new_name='DESCRIPTION',
        ),
    ]
