# Generated by Django 4.2 on 2025-02-02 22:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('root', '0020_rename_content_resume_description'),
    ]

    operations = [
        migrations.RenameField(
            model_name='about',
            old_name='name0',
            new_name='A_LITTLE_ABOUT_US',
        ),
        migrations.RenameField(
            model_name='about',
            old_name='name1',
            new_name='CREATOR_NAME',
        ),
        migrations.RenameField(
            model_name='about',
            old_name='content',
            new_name='DESCRIPTION',
        ),
        migrations.RenameField(
            model_name='about',
            old_name='name10',
            new_name='EMAIL',
        ),
        migrations.RenameField(
            model_name='about',
            old_name='name11',
            new_name='INTERESTS',
        ),
        migrations.RenameField(
            model_name='about',
            old_name='name12',
            new_name='ONLINE_PRESENTATION',
        ),
        migrations.RenameField(
            model_name='about',
            old_name='name2',
            new_name='PAGE_NAME',
        ),
        migrations.RenameField(
            model_name='about',
            old_name='name3',
            new_name='ROLE',
        ),
        migrations.RenameField(
            model_name='about',
            old_name='name4',
            new_name='SERVICES',
        ),
        migrations.RenameField(
            model_name='about',
            old_name='name5',
            new_name='WORK_HISTORY',
        ),
        migrations.RemoveField(
            model_name='about',
            name='name6',
        ),
        migrations.RemoveField(
            model_name='about',
            name='name7',
        ),
        migrations.RemoveField(
            model_name='about',
            name='name8',
        ),
        migrations.RemoveField(
            model_name='about',
            name='name9',
        ),
    ]
