# Generated by Django 4.2 on 2025-02-04 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('root', '0021_rename_name0_about_a_little_about_us_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='reset_code',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='profile_pics/'),
        ),
    ]
