# Generated by Django 4.2 on 2025-02-04 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('root', '0022_remove_userprofile_reset_code_userprofile_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='reset_code',
            field=models.CharField(blank=True, max_length=6, null=True),
        ),
    ]
