# Generated by Django 4.2 on 2025-02-19 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('root', '0025_alter_userprofile_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='image',
            field=models.ImageField(blank=True, default='services/default.jpg', null=True, upload_to='profile_pics/'),
        ),
    ]
