# Generated by Django 4.2 on 2025-02-19 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('root', '0028_alter_userprofile_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='image',
            field=models.ImageField(default='services/default.jpg', upload_to='services'),
        ),
    ]
