# Generated by Django 4.2 on 2025-02-27 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('root', '0031_servicecomment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='name_servise',
            field=models.CharField(default='Default Service', max_length=100),
        ),
    ]
