# Generated by Django 4.2 on 2025-02-27 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('root', '0032_alter_service_name_servise'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicecomment',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
