# Generated by Django 4.2 on 2025-02-27 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('root', '0034_remove_servicecomment_updated_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicecomment',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
