# Generated by Django 4.2 on 2025-02-27 20:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('root', '0035_servicecomment_updated_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='servicecomment',
            name='updated_at',
        ),
    ]
