# Generated by Django 4.2 on 2025-02-28 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('root', '0036_remove_servicecomment_updated_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='image',
            field=models.ImageField(blank=True, default='profile_pics/icon.png', null=True, upload_to='profile_pics/'),
        ),
    ]
