# Generated by Django 4.2 on 2025-02-28 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('root', '0037_alter_userprofile_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='image',
            field=models.ImageField(default='services/default0.jpg', upload_to='services'),
        ),
    ]
