# Generated by Django 4.2 on 2025-03-24 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('root', '0038_alter_service_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Stats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('happy_clients', models.IntegerField(default=0)),
                ('projects', models.IntegerField(default=0)),
                ('hours_of_support', models.IntegerField(default=0)),
                ('hard_workers', models.IntegerField(default=0)),
            ],
        ),
    ]
