# Generated by Django 4.2 on 2025-03-24 18:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('root', '0040_skill'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='servicecomment',
            name='service',
        ),
        migrations.RemoveField(
            model_name='servicecomment',
            name='user',
        ),
        migrations.DeleteModel(
            name='Service',
        ),
        migrations.DeleteModel(
            name='ServiceComment',
        ),
    ]
