# Generated by Django 4.2 on 2025-03-24 18:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('root', '0041_remove_servicecomment_service_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Resume',
        ),
    ]
