# Generated by Django 4.2 on 2025-03-24 19:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('root', '0043_delete_about_delete_skill_delete_stats'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Contact',
        ),
    ]
